fragment HomeParts on Home {
  description
  projects
  skills {
    __typename
    status
    name
    icon
    link
    circlize
  }
}

fragment PostsParts on Posts {
  title
  subtitle
  image
  author
  date
  keywords
  link
  body
}
